import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import { resolve } from 'path';
import { readdirSync, mkdirSync, copyFileSync, statSync } from 'fs';
import { join } from 'path';

/** Recursively copy all .css files from src to dest, preserving subdirectory structure. */
function copyCssRecursive(src: string, dest: string) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath  = join(src, entry);
    const destPath = join(dest, entry);
    if (statSync(srcPath).isDirectory()) {
      copyCssRecursive(srcPath, destPath);
    } else if (entry.endsWith('.css')) {
      copyFileSync(srcPath, destPath);
    }
  }
}

/** Copy publish artifacts that are not generated by Vite itself. */
const copyPublishAssetsPlugin = (): Plugin => ({
  name: 'copy-publish-assets',
  closeBundle() {
    copyCssRecursive('src/styles', 'dist/themes');
  },
});

export default defineConfig({
  plugins: [
    react(),
    dts({
      tsconfigPath: './tsconfig.build.json',
      entryRoot: 'src',
      include: ['src/**/*.ts', 'src/**/*.tsx'],
      exclude: ['src/**/__tests__/**', 'src/**/*.test.*', 'src/test-setup.ts'],
      rollupTypes: true,
      outDir: 'dist',
    }),
    copyPublishAssetsPlugin(),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'WorksCalendar',
      formats: ['es', 'umd'],
      fileName: (format) => `works-calendar.${format}.js`,
    },
    rollupOptions: {
      external: [
        'react', 'react-dom', '@supabase/supabase-js',
        'maplibre-gl', 'maplibre-gl/dist/maplibre-gl.css',
        'react-map-gl', 'react-map-gl/maplibre',
        'exceljs', 'date-fns', 'lucide-react',
      ],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          'date-fns': 'dateFns',
          'lucide-react': 'LucideReact',
        },
        assetFileNames: (info) => info.name === 'works-calendar.css' ? 'style.css' : (info.name ?? '[name][extname]'),
      },
    },
  },
});
