import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import { resolve } from 'path';
import { readdirSync, mkdirSync, copyFileSync } from 'fs';

/** Copy publish artifacts that are not generated by Vite itself. */
const copyPublishAssetsPlugin = (): Plugin => ({
  name: 'copy-publish-assets',
  closeBundle() {
    mkdirSync('dist/themes', { recursive: true });
    readdirSync('src/styles')
      .filter(f => f.endsWith('.css'))
      .forEach(f => copyFileSync(`src/styles/${f}`, `dist/themes/${f}`));
  },
});

export default defineConfig({
  plugins: [
    react(),
    dts({
      tsconfigPath: './tsconfig.build.json',
      entryRoot: 'src',
      include: ['src/**/*.ts', 'src/**/*.tsx'],
      exclude: ['src/**/__tests__/**', 'src/**/*.test.*', 'src/test-setup.ts'],
      rollupTypes: true,
      outDir: 'dist',
    }),
    copyPublishAssetsPlugin(),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'WorksCalendar',
      formats: ['es', 'umd'],
      fileName: (format) => `works-calendar.${format}.js`,
    },
    rollupOptions: {
      external: [
        'react', 'react-dom', 'xlsx', '@supabase/supabase-js',
        'maplibre-gl', 'maplibre-gl/dist/maplibre-gl.css',
        'react-map-gl', 'react-map-gl/maplibre',
      ],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
        },
      },
    },
  },
});
