import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import { resolve } from 'path';
import { readdirSync, mkdirSync, copyFileSync, statSync } from 'fs';
import { join } from 'path';

/** Recursively copy all .css files from src to dest, preserving subdirectory structure. */
function copyCssRecursive(src: string, dest: string) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath  = join(src, entry);
    const destPath = join(dest, entry);
    if (statSync(srcPath).isDirectory()) {
      copyCssRecursive(srcPath, destPath);
    } else if (entry.endsWith('.css') && !entry.endsWith('.module.css')) {
      copyFileSync(srcPath, destPath);
    }
  }
}

/** Copy publish artifacts that are not generated by Vite itself. */
const copyPublishAssetsPlugin = (): Plugin => ({
  name: 'copy-publish-assets',
  closeBundle() {
    copyCssRecursive('src/styles', 'dist/themes');
  },
});

export default defineConfig({
  plugins: [
    react(),
    dts({
      tsconfigPath: './tsconfig.build.json',
      entryRoot: 'src',
      include: ['src/**/*.ts', 'src/**/*.tsx'],
      exclude: ['src/**/__tests__/**', 'src/**/*.test.*', 'src/test-setup.ts'],
      rollupTypes: true,
      outDir: 'dist',
    }),
    copyPublishAssetsPlugin(),
  ],
  build: {
    lib: {
      // Two entries: the core bundle, and the optional .xlsx exporter
      // (published as the `works-calendar/xlsx` subpath) which is the only
      // thing that references `exceljs`. Keeping it a separate entry means
      // a consumer who never imports the subpath never pulls `exceljs`
      // into their build graph.
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        xlsx: resolve(__dirname, 'src/export/excelExport.ts'),
      },
      formats: ['es'],
      fileName: (_format, entryName) =>
        entryName === 'index' ? 'works-calendar.es.js' : `${entryName}.js`,
    },
    rollupOptions: {
      external: [
        'react', 'react-dom', '@supabase/supabase-js',
        'maplibre-gl', 'maplibre-gl/dist/maplibre-gl.css',
        'react-map-gl', 'react-map-gl/maplibre',
        'exceljs', 'date-fns', 'lucide-react',
      ],
      output: {
        assetFileNames: (info) => info.name === 'works-calendar.css' ? 'style.css' : (info.name ?? '[name][extname]'),
      },
    },
  },
});
