/**
 * WorksCalendar — TypeScript Declarations
 * Add "types": "./src/index.d.ts" in package.json or use vite-plugin-dts to generate.
 */
import type * as React from 'react';

// ─── Core types ────────────────────────────────────────────────────────────────

export type ViewType = 'month' | 'week' | 'day' | 'agenda' | 'schedule' | 'timeline';

export type ThemeId =
  | 'light' | 'dark'
  | 'aviation' | 'soft' | 'minimal'
  | 'corporate' | 'forest' | 'ocean';

export type EventStatus = 'confirmed' | 'tentative' | 'cancelled';

export type FieldType = 'text' | 'number' | 'select' | 'date' | 'checkbox' | 'textarea';

// ─── Event ─────────────────────────────────────────────────────────────────────

/** Raw event shape accepted by WorksCalendar (any extra fields pass through). */
export interface WorksCalendarEvent {
  id?: string;
  title: string;
  start: Date | string | number;
  end?: Date | string | number;
  allDay?: boolean;
  category?: string;
  /** Hex color override. If omitted, derived from category. */
  color?: string;
  /** Tail number, person, room, etc. Used for resource grouping. */
  resource?: string;
  /** 'confirmed' (default) | 'tentative' (striped) | 'cancelled' (strikethrough) */
  status?: EventStatus;
  /** Any extra fields — shown in hover card and available to renderEvent. */
  meta?: Record<string, unknown>;
  /** iCal RRULE string, e.g. "FREQ=MONTHLY;INTERVAL=3;COUNT=8" */
  rrule?: string;
  /** Dates excluded from recurring rule (ISO strings or Date objects). */
  exdates?: Array<Date | string>;
}

/** Normalized internal event shape — all fields guaranteed, dates are Date objects. */
export interface NormalizedEvent {
  id: string;
  title: string;
  start: Date;
  end: Date;
  allDay: boolean;
  category: string | null;
  color: string;
  resource: string | null;
  status: EventStatus;
  meta: Record<string, unknown>;
  /** iCal RRULE string preserved from raw event. */
  rrule: string | null;
  /** Dates excluded from the recurrence rule. */
  exdates: Array<Date | string>;
  /** Original raw event passed in. */
  _raw: WorksCalendarEvent;
  /** True for occurrences generated by useOccurrences / rrule expansion. */
  _recurring?: boolean;
  /** Series id — matches the base event id for all occurrences. */
  _seriesId?: string;
  /** Feed label for events sourced from an iCal feed URL. */
  _feedLabel?: string;
  /** Column index within an overlap group (set by layoutOverlaps). */
  _col?: number;
  /** Total columns in the overlap group (set by layoutOverlaps). */
  _numCols?: number;
}

// ─── Notes ─────────────────────────────────────────────────────────────────────

export interface Note {
  id: string;
  eventId: string;
  body: string;
  author?: string;
  createdAt?: string;
  updatedAt?: string;
}

// ─── Config ────────────────────────────────────────────────────────────────────

export interface FieldDefinition {
  name: string;
  type: FieldType;
  required?: boolean;
  /** Comma-separated option list for type='select'. */
  options?: string;
}

export interface HoverCardConfig {
  showTime?: boolean;
  showCategory?: boolean;
  showResource?: boolean;
  showMeta?: boolean;
  showNotes?: boolean;
}

export interface DisplayConfig {
  defaultView?: ViewType;
  weekStartDay?: 0 | 1;
  /** First visible hour in week/day views (0–23). Default 6. */
  dayStart?: number;
  /** Last visible hour in week/day views (1–24). Default 22. */
  dayEnd?: number;
  showWeekNumbers?: boolean;
  /** Month view: animate a hovered week row to 150% height for easier reading. */
  enlargeMonthRowOnHover?: boolean;
}

export interface CalendarConfig {
  hoverCard?: HoverCardConfig;
  /** Map of category name → custom field definitions. */
  eventFields?: Record<string, FieldDefinition[]>;
  display?: DisplayConfig;
  access?: { viewerPassword?: string };
}

// ─── Saved Views ───────────────────────────────────────────────────────────────

export interface SavedView {
  id: string;
  name: string;
  createdAt: string;
  color: string | null;
  /** Optional pinned calendar view (e.g. 'month', 'week'). */
  view: string | null;
  filters: Record<string, unknown>;
}

export declare function useSavedViews(calendarId: string): {
  views: SavedView[];
  saveView: (name: string, filters: object, opts?: { color?: string; view?: string }) => SavedView;
  updateView: (id: string, patch: Partial<SavedView>) => void;
  resaveView: (id: string, filters: object, viewName?: string) => void;
  deleteView: (id: string) => void;
};

// ─── Filter schema ─────────────────────────────────────────────────────────────

export type FilterFieldType = 'select' | 'multi-select' | 'date-range' | 'text' | 'boolean' | 'custom';

export interface FilterOption {
  label: string;
  value: string | number | boolean;
  color?: string;
  icon?: string;
}

export interface FilterField {
  key: string;
  label: string;
  type: FilterFieldType;
  options?: FilterOption[];
  placeholder?: string;
  searchable?: boolean;
  clearable?: boolean;
  defaultValue?: unknown;
  pillLabel?: (value: unknown) => string;
  predicate?: (item: unknown, value: unknown) => boolean;
  getOptions?: (items: unknown[]) => FilterOption[];
  hidden?: boolean | ((ctx: { items: unknown[]; filters: Record<string, unknown> }) => boolean);
}

export declare const DEFAULT_FILTER_SCHEMA: FilterField[];

/**
 * Pre-built field factories for common filter dimensions.
 * Each accepts an optional overrides object to customise key/label/options/predicate.
 *
 * @example
 * import { DEFAULT_FILTER_SCHEMA, statusField, priorityField } from 'works-calendar';
 * const schema = [...DEFAULT_FILTER_SCHEMA, statusField(), priorityField()];
 */
export declare function statusField(overrides?: Partial<FilterField>): FilterField;
export declare function priorityField(overrides?: Partial<FilterField>): FilterField;
export declare function ownerField(overrides?: Partial<FilterField>): FilterField;
export declare function tagsField(overrides?: Partial<FilterField>): FilterField;
/**
 * Generic single-value meta field (select).
 * @param metaKey — the meta property name, e.g. 'department'
 */
export declare function metaSelectField(metaKey: string, overrides?: Partial<FilterField>): FilterField;

// ─── Filters ───────────────────────────────────────────────────────────────────

export interface FilterState {
  categories: Set<string>;
  resources: Set<string>;
  dateRange: { start: Date; end: Date } | null;
  search: string;
}

// ─── Rendering ─────────────────────────────────────────────────────────────────

export interface RenderEventContext {
  /** Which view is rendering this event. */
  view: ViewType;
  /** True in compact views (month cell, schedule cell). */
  isCompact: boolean;
  /** Call this to fire the default onEventClick handler. */
  onClick: () => void;
  /** Effective resolved color after colorRules applied. */
  color: string;
}

export interface ColorRule {
  /** Return true to apply this rule's color. Rules are checked in order. */
  when: (event: NormalizedEvent) => boolean;
  color: string;
}

// ─── Validation ────────────────────────────────────────────────────────────────

/** A time window during which events are blocked (hard violation). */
export interface BlockedWindow {
  start: Date | string;
  end: Date | string;
  /** If set, only events with a matching resource are blocked. */
  resource?: string;
  /** Human-readable reason shown in the validation alert. */
  reason?: string;
}

export interface Violation {
  rule: 'invalid-duration' | 'blocked-window' | 'overlap' | 'outside-business-hours' | string;
  severity: 'hard' | 'soft';
  message: string;
  conflictingEvent?: NormalizedEvent;
}

export interface ValidationResult {
  /** False when any hard violation is present. */
  allowed: boolean;
  severity: 'none' | 'soft' | 'hard';
  violations: Violation[];
  suggestedChange: null;
}

export interface ValidationChange {
  type: 'create' | 'move' | 'resize';
  event: NormalizedEvent | null;
  newStart: Date;
  newEnd: Date;
  resource?: string | null;
}

export interface ValidationContext {
  events?: NormalizedEvent[];
  businessHours?: BusinessHours;
  blockedWindows?: BlockedWindow[];
}

// ─── iCal ──────────────────────────────────────────────────────────────────────

export interface ICalFeed {
  /** Full URL to an .ics feed (https:// or webcal://). */
  url: string;
  label?: string;
  /** Re-fetch interval in milliseconds. Default: 300_000 (5 min). */
  refreshInterval?: number;
}

export interface ParseICSOptions {
  /** Range to expand recurring events into. Defaults to ±1 year from today. */
  rangeStart?: Date;
  rangeEnd?: Date;
}

// ─── Async data ────────────────────────────────────────────────────────────────

export interface FetchEventsParams {
  start: Date;
  end: Date;
  signal?: AbortSignal;
}

// ─── Imperative API ────────────────────────────────────────────────────────────

export interface CalendarApi {
  /** Navigate to any date. */
  navigateTo: (date: Date) => void;
  /** Switch views programmatically. */
  setView: (view: ViewType) => void;
  /** Jump to today. */
  goToToday: () => void;
  /** Open the hover card for a specific event by id. */
  openEvent: (eventId: string) => void;
  /** Return the currently visible (filtered) events. */
  getVisibleEvents: () => NormalizedEvent[];
  /** Clear all active filters. */
  clearFilters: () => void;
  /** Trigger the "Add Event" form. */
  addEvent: (defaults?: Partial<WorksCalendarEvent>) => void;
}

// ─── Business hours ────────────────────────────────────────────────────────────

export interface BusinessHours {
  /** Start hour (0–23). Default: 9. */
  start: number;
  /** End hour (1–24). Default: 17. */
  end: number;
  /** Day-of-week numbers that are business days (0=Sun, 6=Sat). Default: [1,2,3,4,5]. */
  days?: number[];
}

// ─── Main component ────────────────────────────────────────────────────────────

export interface WorksCalendarProps {
  // ── Data ──
  /** Static event array. If fetchEvents is also provided, both sources are merged. */
  events?: WorksCalendarEvent[];
  /**
   * Async function to load events for a date range.
   * Called whenever the visible range changes (navigation).
   * Return an array of WorksCalendarEvent.
   */
  fetchEvents?: (params: FetchEventsParams) => Promise<WorksCalendarEvent[]>;
  /** Live iCal feed URLs to subscribe to. */
  icalFeeds?: ICalFeed[];

  // ── Identity ──
  /** Namespaces localStorage (config, profiles). Default: 'default'. */
  calendarId?: string;

  // ── Owner config ──
  ownerPassword?: string;
  onConfigSave?: (config: CalendarConfig) => void;

  // ── Notes ──
  notes?: Record<string, Note>;
  onNoteSave?: (note: Partial<Note>) => void;
  onNoteDelete?: (noteId: string) => void;

  // ── Event callbacks ──
  onEventClick?: (event: NormalizedEvent) => void;
  /** Called from the form when an event is created or edited. */
  onEventSave?: (event: WorksCalendarEvent) => void;
  /**
   * Called when the user drags an event to a new time or day.
   * Receives the normalized event plus the new start/end.
   * Falls back to onEventSave if not provided.
   */
  onEventMove?: (event: NormalizedEvent, newStart: Date, newEnd: Date) => void;
  /**
   * Called when the user drags the resize handle to a new end time.
   * Falls back to onEventSave if not provided.
   */
  onEventResize?: (event: NormalizedEvent, newStart: Date, newEnd: Date) => void;
  onEventDelete?: (eventId: string) => void;
  /**
   * Called when the user selects an empty time range — either by dragging
   * on the time grid (week/day) or clicking a day cell (month).
   * Receives the selected start and end as Date objects.
   * Only fires when the calendar has an add button (showAddButton or owner mode).
   */
  onDateSelect?: (start: Date, end: Date) => void;
  /** Called when events are imported via drag-drop or feed. */
  onImport?: (events: WorksCalendarEvent[]) => void;

  // ── Supabase realtime ──
  supabaseUrl?: string;
  supabaseKey?: string;
  /** Table to subscribe to for realtime event updates. */
  supabaseTable?: string;
  /** Supabase PostgREST filter, e.g. "calendar_id=eq.my-cal". */
  supabaseFilter?: string;

  // ── Validation ──
  /**
   * Time windows that are hard-blocked — any event overlapping a window is
   * rejected before the host's onEventSave/onEventMove/onEventResize fires.
   * A window with no `resource` blocks all events during that period.
   */
  blockedWindows?: BlockedWindow[];

  // ── Appearance ──
  theme?: ThemeId;
  /**
   * Conditional color overrides. Checked in order — first match wins.
   * @example [{ when: e => e.category === 'AOG', color: '#ef4444' }]
   */
  colorRules?: ColorRule[];
  /** Shade non-business hours in week/day views. */
  businessHours?: BusinessHours;

  // ── Custom rendering ──
  /**
   * Replace the default event pill/bar with your own component.
   * The positioning wrapper is always rendered by the view;
   * you control the inner content and styling.
   */
  renderEvent?: (event: NormalizedEvent, context: RenderEventContext) => React.ReactNode;
  /**
   * Replace the default hover card with a custom component.
   * Call onClose() to dismiss it.
   */
  renderHoverCard?: (event: NormalizedEvent, onClose: () => void) => React.ReactNode;
  /**
   * Replace the entire toolbar. Receives the imperative CalendarApi.
   */
  renderToolbar?: (api: CalendarApi) => React.ReactNode;
  /**
   * Custom empty state shown when no events match current filters.
   */
  emptyState?: React.ReactNode;

  // ── UI toggles ──
  /** Show the "Add Event" button. Always shown when owner is authenticated. */
  showAddButton?: boolean;

  // ── Imperative handle ──
  ref?: React.Ref<CalendarApi>;
}

// ─── Component ─────────────────────────────────────────────────────────────────

export declare const WorksCalendar: React.ForwardRefExoticComponent<
  WorksCalendarProps & React.RefAttributes<CalendarApi>
>;

// ─── Hooks ─────────────────────────────────────────────────────────────────────

export declare function useCalendar(
  rawEvents: WorksCalendarEvent[],
  initialView?: ViewType
): {
  view: ViewType;
  setView: (v: ViewType) => void;
  currentDate: Date;
  setCurrentDate: (d: Date) => void;
  events: NormalizedEvent[];
  visibleEvents: NormalizedEvent[];
  categories: string[];
  resources: string[];
  filters: FilterState;
  navigate: (direction: -1 | 1) => void;
  goToToday: () => void;
  toggleCategory: (cat: string) => void;
  toggleResource: (res: string) => void;
  setSearch: (q: string) => void;
  setDateRange: (range: FilterState['dateRange']) => void;
  clearFilters: () => void;
  replaceFilters: (filters: FilterState) => void;
};

export declare function useRealtimeEvents(opts: {
  supabaseClient: unknown;
  table?: string;
  filter?: string;
}): {
  events: WorksCalendarEvent[];
  status: 'connecting' | 'live' | 'error' | 'disabled';
};

export declare function useDrag(opts: {
  pxPerHour: number;
  dayStart: number;
  dayEnd: number;
}): {
  ghost: { ev: NormalizedEvent; start: Date; end: Date } | null;
  draggedId: string | null;
  /** Pass gridEl once here; it is stored internally for subsequent moves. */
  startMove: (ev: NormalizedEvent, e: React.PointerEvent, gridEl: HTMLElement, days: Date[], gutterWidth: number) => void;
  startResize: (ev: NormalizedEvent, e: React.PointerEvent, gridEl: HTMLElement, days: Date[], gutterWidth: number) => void;
  /** No gridEl arg — stored from startMove/startResize. */
  onPointerMove: (e: React.PointerEvent) => void;
  onPointerUp: () => { ev: NormalizedEvent; newStart: Date; newEnd: Date; type: 'move' | 'resize' } | null;
  cancel: () => void;
};

export declare function useOccurrences(
  events: NormalizedEvent[],
  rangeStart: Date,
  rangeEnd: Date,
): NormalizedEvent[];

export declare function useFeedEvents(icalFeeds: ICalFeed[] | undefined): {
  feedEvents: WorksCalendarEvent[];
  feedErrors: Array<{ feed: ICalFeed; err: Error }>;
};

// ─── Utilities ─────────────────────────────────────────────────────────────────

export declare function parseICS(
  text: string,
  options?: ParseICSOptions
): WorksCalendarEvent[];

export declare function fetchAndParseICS(
  url: string,
  options?: ParseICSOptions
): Promise<WorksCalendarEvent[]>;

export declare function normalizeEvent(raw: WorksCalendarEvent): NormalizedEvent;
export declare function normalizeEvents(raw: WorksCalendarEvent[]): NormalizedEvent[];
export declare function exportToExcel(events: NormalizedEvent[], filename?: string): Promise<void>;

// ─── Layout utilities ──────────────────────────────────────────────────────────

export interface SpanLayout {
  ev: NormalizedEvent;
  /** 0-based column index of the first day this event covers in the row. */
  startCol: number;
  /** 0-based column index of the last day this event covers in the row. */
  endCol: number;
  /** Lane (row) index within the all-day area. */
  lane: number;
  continuesBefore: boolean;
  continuesAfter: boolean;
}

/**
 * Assign overlap columns to timed events that share time slots.
 * Augments each event with `_col` and `_numCols`.
 */
export declare function layoutOverlaps(events: NormalizedEvent[]): NormalizedEvent[];

/**
 * Lane-pack multi-day / all-day events across a week row.
 */
export declare function layoutSpans(
  events: NormalizedEvent[],
  weekStart: Date,
  weekEnd: Date,
): SpanLayout[];

/**
 * Return the display end date for an event.
 * For all-day events, subtracts 1 day from the exclusive end.
 * For timed events ending at midnight, treats the end as the previous day.
 */
export declare function displayEndDay(ev: NormalizedEvent): Date;

// ─── Validation ────────────────────────────────────────────────────────────────

/**
 * Run the shared validation pipeline against a proposed change.
 * Can be called from outside WorksCalendar (e.g. custom toolbars, forms).
 */
export declare function validateChange(
  change: ValidationChange,
  context?: ValidationContext,
): ValidationResult;

// ─── Theme metadata ────────────────────────────────────────────────────────────

export interface ThemeDefinition {
  id: ThemeId;
  label: string;
  description: string;
  dark: boolean;
  preview: {
    bg: string;
    surface: string;
    accent: string;
    text: string;
    border: string;
  };
}

export declare const THEMES: ThemeDefinition[];
export declare const THEMES_BY_ID: Record<ThemeId, ThemeDefinition>;
export declare const THEME_IDS: ThemeId[];

export declare const FIELD_TYPES: Array<{ value: FieldType; label: string }>;

// ─── API v1: versioned public schema ──────────────────────────────────────────

// Re-exports everything from the versioned public schema layer.
// Consumers can also import directly from 'works-calendar/api/v1'.
export * from './api/v1/index';
